steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/test-cloudbuild-image:$COMMIT_SHA',
        '-t', 'gcr.io/$PROJECT_ID/test-cloudbuild-image:latest',
        '.' 
        ]
    env:
      'COMMIT_SHA=$COMMIT_SHA'
images:
- 'gcr.io/$PROJECT_ID/test-cloudbuild-image:latest'
